// Code generated by zip; DO NOT EDIT.

package info

import (
	"encoding/binary"
	"fmt"
	"strings"

	types "github.com/luxfi/api/types"
	ids "github.com/luxfi/ids"
	zap "github.com/zap-proto/go"
)

// ---- GetBlockchainIDArgs -----------------------------------------------

const (
	getBlockchainIDArgsAliasAt = 0
	getBlockchainIDArgsSize    = 8
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*GetBlockchainIDArgs)(nil)

// MarshalZAP writes GetBlockchainIDArgs from constant offsets.
func (x *GetBlockchainIDArgs) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(getBlockchainIDArgsSize + 256)
	ob := b.StartObject(getBlockchainIDArgsSize)
	ob.SetText(getBlockchainIDArgsAliasAt, string(x.Alias))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads GetBlockchainIDArgs out of the buffer that arrived.
func (x *GetBlockchainIDArgs) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("GetBlockchainIDArgs: %w", err)
	}
	o := m.Root()
	x.Alias = string(strings.Clone(o.Text(getBlockchainIDArgsAliasAt)))
	return nil
}

// ---- GetBlockchainIDReply ----------------------------------------------

const (
	getBlockchainIDReplyBlockchainIDAt = 0
	getBlockchainIDReplySize           = 32
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*GetBlockchainIDReply)(nil)

// MarshalZAP writes GetBlockchainIDReply from constant offsets.
func (x *GetBlockchainIDReply) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(getBlockchainIDReplySize + 256)
	ob := b.StartObject(getBlockchainIDReplySize)
	ob.SetBytesFixed(getBlockchainIDReplyBlockchainIDAt, x.BlockchainID[:])
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads GetBlockchainIDReply out of the buffer that arrived.
func (x *GetBlockchainIDReply) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("GetBlockchainIDReply: %w", err)
	}
	o := m.Root()
	copy(x.BlockchainID[:], o.BytesFixed(getBlockchainIDReplyBlockchainIDAt, 32))
	return nil
}

// ---- GetNetworkIDReply -------------------------------------------------

const (
	getNetworkIDReplyNetworkIDAt = 0
	getNetworkIDReplySize        = 8
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*GetNetworkIDReply)(nil)

// MarshalZAP writes GetNetworkIDReply from constant offsets.
func (x *GetNetworkIDReply) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(getNetworkIDReplySize + 256)
	ob := b.StartObject(getNetworkIDReplySize)
	ob.SetUint32(getNetworkIDReplyNetworkIDAt, uint32(x.NetworkID))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads GetNetworkIDReply out of the buffer that arrived.
func (x *GetNetworkIDReply) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("GetNetworkIDReply: %w", err)
	}
	o := m.Root()
	x.NetworkID = types.Uint32(o.Uint32(getNetworkIDReplyNetworkIDAt))
	return nil
}

// ---- GetNetworkNameReply -----------------------------------------------

const (
	getNetworkNameReplyNetworkNameAt = 0
	getNetworkNameReplySize          = 8
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*GetNetworkNameReply)(nil)

// MarshalZAP writes GetNetworkNameReply from constant offsets.
func (x *GetNetworkNameReply) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(getNetworkNameReplySize + 256)
	ob := b.StartObject(getNetworkNameReplySize)
	ob.SetText(getNetworkNameReplyNetworkNameAt, string(x.NetworkName))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads GetNetworkNameReply out of the buffer that arrived.
func (x *GetNetworkNameReply) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("GetNetworkNameReply: %w", err)
	}
	o := m.Root()
	x.NetworkName = string(strings.Clone(o.Text(getNetworkNameReplyNetworkNameAt)))
	return nil
}

// ---- GetNodeIDReply ----------------------------------------------------

const (
	getNodeIDReplyNodeIDAt  = 0
	getNodeIDReplyNodePOPAt = 24
	getNodeIDReplySize      = 32
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*GetNodeIDReply)(nil)

// MarshalZAP writes GetNodeIDReply from constant offsets.
func (x *GetNodeIDReply) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(getNodeIDReplySize + 256)
	ob := b.StartObject(getNodeIDReplySize)
	ob.SetBytesFixed(getNodeIDReplyNodeIDAt, x.NodeID[:])
	if x.NodePOP != nil {
		innerNodePOP, err := x.NodePOP.MarshalZAP()
		if err != nil {
			return nil, err
		}
		ob.SetBytes(getNodeIDReplyNodePOPAt, innerNodePOP)
	}
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads GetNodeIDReply out of the buffer that arrived.
func (x *GetNodeIDReply) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("GetNodeIDReply: %w", err)
	}
	o := m.Root()
	copy(x.NodeID[:], o.BytesFixed(getNodeIDReplyNodeIDAt, 20))
	if raw := o.Bytes(getNodeIDReplyNodePOPAt); len(raw) > 0 {
		var v ProofOfPossession
		if err := v.UnmarshalZAP(raw); err != nil {
			return err
		}
		x.NodePOP = &v
	}
	return nil
}

// ---- GetNodeIPReply ----------------------------------------------------

const (
	getNodeIPReplyIPAt = 0
	getNodeIPReplySize = 8
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*GetNodeIPReply)(nil)

// MarshalZAP writes GetNodeIPReply from constant offsets.
func (x *GetNodeIPReply) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(getNodeIPReplySize + 256)
	ob := b.StartObject(getNodeIPReplySize)
	{
		eb := zap.NewBuilder(zap.HeaderSize)
		eb.StartObject(0).FinishAsRoot()
		ob.SetBytes(getNodeIPReplyIPAt, eb.Finish())
	}
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads GetNodeIPReply out of the buffer that arrived.
func (x *GetNodeIPReply) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("GetNodeIPReply: %w", err)
	}
	_ = m
	return nil
}

// ---- GetTxFeeResponse --------------------------------------------------

const (
	getTxFeeResponseTxFeeAt                  = 0
	getTxFeeResponseCreateAssetTxFeeAt       = 8
	getTxFeeResponseCreateNetworkTxFeeAt     = 16
	getTxFeeResponseTransformChainTxFeeAt    = 24
	getTxFeeResponseCreateChainTxFeeAt       = 32
	getTxFeeResponseAddNetworkValidatorFeeAt = 40
	getTxFeeResponseAddNetworkDelegatorFeeAt = 48
	getTxFeeResponseSize                     = 56
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*GetTxFeeResponse)(nil)

// MarshalZAP writes GetTxFeeResponse from constant offsets.
func (x *GetTxFeeResponse) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(getTxFeeResponseSize + 256)
	ob := b.StartObject(getTxFeeResponseSize)
	ob.SetUint64(getTxFeeResponseTxFeeAt, uint64(x.TxFee))
	ob.SetUint64(getTxFeeResponseCreateAssetTxFeeAt, uint64(x.CreateAssetTxFee))
	ob.SetUint64(getTxFeeResponseCreateNetworkTxFeeAt, uint64(x.CreateNetworkTxFee))
	ob.SetUint64(getTxFeeResponseTransformChainTxFeeAt, uint64(x.TransformChainTxFee))
	ob.SetUint64(getTxFeeResponseCreateChainTxFeeAt, uint64(x.CreateChainTxFee))
	ob.SetUint64(getTxFeeResponseAddNetworkValidatorFeeAt, uint64(x.AddNetworkValidatorFee))
	ob.SetUint64(getTxFeeResponseAddNetworkDelegatorFeeAt, uint64(x.AddNetworkDelegatorFee))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads GetTxFeeResponse out of the buffer that arrived.
func (x *GetTxFeeResponse) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("GetTxFeeResponse: %w", err)
	}
	o := m.Root()
	x.TxFee = types.Uint64(o.Uint64(getTxFeeResponseTxFeeAt))
	x.CreateAssetTxFee = types.Uint64(o.Uint64(getTxFeeResponseCreateAssetTxFeeAt))
	x.CreateNetworkTxFee = types.Uint64(o.Uint64(getTxFeeResponseCreateNetworkTxFeeAt))
	x.TransformChainTxFee = types.Uint64(o.Uint64(getTxFeeResponseTransformChainTxFeeAt))
	x.CreateChainTxFee = types.Uint64(o.Uint64(getTxFeeResponseCreateChainTxFeeAt))
	x.AddNetworkValidatorFee = types.Uint64(o.Uint64(getTxFeeResponseAddNetworkValidatorFeeAt))
	x.AddNetworkDelegatorFee = types.Uint64(o.Uint64(getTxFeeResponseAddNetworkDelegatorFeeAt))
	return nil
}

// ---- IsBootstrappedArgs ------------------------------------------------

const (
	isBootstrappedArgsChainAt = 0
	isBootstrappedArgsSize    = 8
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*IsBootstrappedArgs)(nil)

// MarshalZAP writes IsBootstrappedArgs from constant offsets.
func (x *IsBootstrappedArgs) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(isBootstrappedArgsSize + 256)
	ob := b.StartObject(isBootstrappedArgsSize)
	ob.SetText(isBootstrappedArgsChainAt, string(x.Chain))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads IsBootstrappedArgs out of the buffer that arrived.
func (x *IsBootstrappedArgs) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("IsBootstrappedArgs: %w", err)
	}
	o := m.Root()
	x.Chain = string(strings.Clone(o.Text(isBootstrappedArgsChainAt)))
	return nil
}

// ---- IsBootstrappedResponse --------------------------------------------

const (
	isBootstrappedResponseIsBootstrappedAt = 0
	isBootstrappedResponseSize             = 8
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*IsBootstrappedResponse)(nil)

// MarshalZAP writes IsBootstrappedResponse from constant offsets.
func (x *IsBootstrappedResponse) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(isBootstrappedResponseSize + 256)
	ob := b.StartObject(isBootstrappedResponseSize)
	ob.SetBool(isBootstrappedResponseIsBootstrappedAt, bool(x.IsBootstrapped))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads IsBootstrappedResponse out of the buffer that arrived.
func (x *IsBootstrappedResponse) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("IsBootstrappedResponse: %w", err)
	}
	o := m.Root()
	x.IsBootstrapped = bool(o.Bool(isBootstrappedResponseIsBootstrappedAt))
	return nil
}

// ---- PeersArgs ---------------------------------------------------------

const (
	peersArgsNodeIDsAt = 0
	peersArgsSize      = 8
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*PeersArgs)(nil)

// MarshalZAP writes PeersArgs from constant offsets.
func (x *PeersArgs) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(peersArgsSize + 256)
	nodeIDsAt, nodeIDsN := 0, len(x.NodeIDs)
	if nodeIDsN > 0 {
		var blob []byte
		for i := range x.NodeIDs {
			enc := x.NodeIDs[i][:]
			var n [4]byte
			binary.LittleEndian.PutUint32(n[:], uint32(len(enc)))
			blob = append(blob, n[:]...)
			blob = append(blob, enc...)
		}
		nodeIDsAt = b.WriteBytes(blob)
	}
	ob := b.StartObject(peersArgsSize)
	if nodeIDsN > 0 {
		ob.SetList(peersArgsNodeIDsAt, nodeIDsAt, nodeIDsN)
	}
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads PeersArgs out of the buffer that arrived.
func (x *PeersArgs) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("PeersArgs: %w", err)
	}
	o := m.Root()
	if l := o.List(peersArgsNodeIDsAt); l.Len() > 0 {
		rows := make([]ids.NodeID, l.Len())
		for i := range rows {
			copy(rows[i][:], l.BytesAt(i))
		}
		x.NodeIDs = rows
	}
	return nil
}

// ---- ProofOfPossession -------------------------------------------------

const (
	proofOfPossessionPublicKeyAt         = 0
	proofOfPossessionProofOfPossessionAt = 8
	proofOfPossessionSize                = 16
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*ProofOfPossession)(nil)

// MarshalZAP writes ProofOfPossession from constant offsets.
func (x *ProofOfPossession) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(proofOfPossessionSize + 256)
	ob := b.StartObject(proofOfPossessionSize)
	ob.SetText(proofOfPossessionPublicKeyAt, string(x.PublicKey))
	ob.SetText(proofOfPossessionProofOfPossessionAt, string(x.ProofOfPossession))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads ProofOfPossession out of the buffer that arrived.
func (x *ProofOfPossession) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("ProofOfPossession: %w", err)
	}
	o := m.Root()
	x.PublicKey = string(strings.Clone(o.Text(proofOfPossessionPublicKeyAt)))
	x.ProofOfPossession = string(strings.Clone(o.Text(proofOfPossessionProofOfPossessionAt)))
	return nil
}

// ---- UptimeResponse ----------------------------------------------------

const (
	uptimeResponseRewardingStakePercentageAt  = 0
	uptimeResponseWeightedAveragePercentageAt = 8
	uptimeResponseSize                        = 16
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*UptimeResponse)(nil)

// MarshalZAP writes UptimeResponse from constant offsets.
func (x *UptimeResponse) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(uptimeResponseSize + 256)
	ob := b.StartObject(uptimeResponseSize)
	ob.SetFloat64(uptimeResponseRewardingStakePercentageAt, float64(x.RewardingStakePercentage))
	ob.SetFloat64(uptimeResponseWeightedAveragePercentageAt, float64(x.WeightedAveragePercentage))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads UptimeResponse out of the buffer that arrived.
func (x *UptimeResponse) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("UptimeResponse: %w", err)
	}
	o := m.Root()
	x.RewardingStakePercentage = types.Float64(o.Float64(uptimeResponseRewardingStakePercentageAt))
	x.WeightedAveragePercentage = types.Float64(o.Float64(uptimeResponseWeightedAveragePercentageAt))
	return nil
}
