// Code generated by zip; DO NOT EDIT.

package health

import (
	"encoding/binary"
	"fmt"

	zap "github.com/zap-proto/go"
)

// ---- APIArgs -----------------------------------------------------------

const (
	aPIArgsTagsAt = 0
	aPIArgsSize   = 8
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*APIArgs)(nil)

// MarshalZAP writes APIArgs from constant offsets.
func (x *APIArgs) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(aPIArgsSize + 256)
	tagsAt, tagsN := 0, len(x.Tags)
	if tagsN > 0 {
		var blob []byte
		for i := range x.Tags {
			enc := []byte(x.Tags[i])
			var n [4]byte
			binary.LittleEndian.PutUint32(n[:], uint32(len(enc)))
			blob = append(blob, n[:]...)
			blob = append(blob, enc...)
		}
		tagsAt = b.WriteBytes(blob)
	}
	ob := b.StartObject(aPIArgsSize)
	if tagsN > 0 {
		ob.SetList(aPIArgsTagsAt, tagsAt, tagsN)
	}
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads APIArgs out of the buffer that arrived.
func (x *APIArgs) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("APIArgs: %w", err)
	}
	o := m.Root()
	if l := o.List(aPIArgsTagsAt); l.Len() > 0 {
		rows := make([]string, l.Len())
		for i := range rows {
			rows[i] = string(l.BytesAt(i))
		}
		x.Tags = rows
	}
	return nil
}
